### ISSUE TITLE
Allow passwordless authentification

### ISSUE THREAD

**Issue by GaetanLepage** [jonhoo/obs-do#1]
First, thank you for developing this tool !

If the user disables authentication in the OBS WebSocket settings, no password is required to connect to the websocket.
However, currently `obs-do` enforces a token file to exist in `~/.config`.

Would you agree leaving the user the possibility to connect to the server without a password ?
Right now, the tool crashes if the token file is missing.
Maybe we could set the password to `""` by default and try connecting with that.
We could then hint the user to create the token file if the connection fails.

I tried it and it works fine.
What do you think ?

**Comment by jonhoo** [comment]
Hi there! Sure, I'd be happy to take a PR that makes the token file optional, and uses passwordless if it is missing. It's probably worth emitting a special error in the case where authentication fails when the token file doesn't exist though.

**Comment by GaetanLepage** [comment]
> Hi there! Sure, I'd be happy to take a PR that makes the token file optional, and uses passwordless if it is missing. It's probably worth emitting a special error in the case where authentication fails when the token file doesn't exist though.

Thanks !
I will try to give it a shot then :)
